### ISSUE TITLE
MDS v3.0

### ISSUE THREAD

**Issue by alvinlee001** [line/line-fido2-server#11]
Hi, I would like to know if there are any updates regarding the MDS implementation, will this repo comply to the latest MDS v3.0a any time soon?

https://fidoalliance.org/metadata/

**Comment by kj84park** [comment]
Hello, we are considering updating the MDS to v3. 
But it might take some time. Please understand.

**Comment by Saebyeol98** [comment]
해당 사항에 대해서 진행상황을 공유 해주실 수 있나요? @kj84park FIDO 얼라이언스 측에서 보면 2022년 10월부로 fido2 mdsV2 에대한 완벽한 지원이 끝난다고 v3로 마이그레이트 하는걸 권장한다고 나와있습니다

https://fidoalliance.org/legacy-mds2-information/

As of May 2021, Metadata Service 2 has been deprecated and replaced with Metadata Service 3. To read more about MDS3 it please visit https://fidoalliance.org/metadata. MDS2 will be fully operational for additional 18 months or until October 2022. It is highly encouraged to begin migrating to MDS3.

**Comment by JyotirGodavarthi** [comment]
Any updates on the migration to MDS3?

**Comment by kj84park** [comment]
We'll be adding that implementation soon. Sorry for being late.
