### ISSUE TITLE
Add API Guide and Tests made with Spring RestDocs for rp-server

### ISSUE THREAD

**Issue by kj84park** [line/line-fido2-server#19]
In the case of the server app(FIDO2 Server), the API Guide of Spring RestDocs has already been completed. 

However, it does not exist for rpserver yet. 
The API Guide can be configured by referring to the following.

## references
- [Official Spring RestDocs Guide](https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/)
- https://github.com/line/line-fido2-server/pull/10

#### Configuration
- [Api-guide.adoc](https://github.com/line/line-fido2-server/blob/main/server/src/docs/asciidoc/api-guide.adoc)
- [Tests](https://github.com/line/line-fido2-server/tree/main/server/src/test/java/com/linecorp/line/auth/fido/fido2/server/controller)
  - [Dummy data for tests](https://github.com/line/line-fido2-server/tree/main/server/src/test/resources)
- [Build settings](https://github.com/line/line-fido2-server/blob/96183ba12d23094f4bd7d9c98ecd3a711f81ff5b/server/build.gradle#L45-L68)
- [Api-guide.html](https://github.com/line/line-fido2-server/blob/main/server/src/main/resources/static/docs/api-guide.html)
#### How to open
- [Readme](https://github.com/line/line-fido2-server#spring-rest-docs)

**Comment by simple** [comment]
I'd like to work on this. :)

**Comment by kj84park** [comment]
> I'd like to work on this. :)

Sure! Thank you for your contribution!
