### ISSUE TITLE
Improve message validation check 

### ISSUE THREAD

**Issue by kj84park** [line/line-fido2-server#3]
When a message is entered into the controller,
The controller calls the following logic to verify the message.

`ReqMsgVerifier.validateRegOptionRequest(regOptionRequest);`

We expect this logic to be improved with `Spring Boot Bean Validation`.

**Comment by seachicken** [comment]
Can I take up this issue?

**Comment by kj84park** [comment]
> Can I take up this issue?

Of course! Thank you!
