### ISSUE TITLE
docker-compose up - error

### ISSUE THREAD

**Issue by hygjob** [line/line-fido2-server#48]
Hello. When I use docker, I got error below.
I use window 10 and docker.

D:\line-fido2-server>docker-compose up
[+] Running 0/3
 - fido2 Warning                                                                                                   4.3s
 - build Warning                                                                                                   3.1s
 - rp Warning                                                                                                      4.4s
[+] Building 4.1s (14/20)
...
...
------
 > [rp:latest] FROM docker.io/library/build-image:latest:
------
failed to solve: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

D:\line-fido2-server>

**Comment by hugomoraismendes** [comment]
The same problem is happening to me on Linux/Ubuntu and Mac Os

**Comment by kj84park** [comment]
This issue was resolved in https://github.com/line/line-fido2-server/pull/56
